version: '3.8'

services:
  mysql:
    image: mysql:8.1.0
    container_name: mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    networks:
      - july

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: "root"
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - july

networks:
  july:
    driver: bridge