server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/football_league?createDatabaseIfNotExist=true
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root


  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
